export const columnNamesLayer1 = {
  "marker-symbol": "Тип",
  "name": "Название",
  "address": "Адрес",
  "Действие": "Действие"
};

export const columnNamesLayer2 = {
  "id": "ID",
  "Название_ru": "Название (рус)",
  "Name_en": "Название (англ)",
  "id_станции": "ID станции",
  "Направление": "Направление",
  "lat": "Широта",
  "lon": "Долгота",
  "Действие": "Действие"
};

export const columnNamesLayer3 = {
  "orbis_id": "Orbis ID",
  "name": "Имя",
  "category": "Категория",
  "value": "Значение",
  "num1": "Номер_1",
  "tocreate": "Задача",
  "profile": "Профиль",
  "status2": "Статус",
  "reg_date": "Дата регистрации",
  "to_create": "Дата создания",
  "documents": "Документы",
  "department": "Отдел",
  "international1": "Международный_1",
  "international2": "Международный_2",
  "num2": "Номер_2",
  "address": "Адрес",
  "descript": "Описание",
  "area_fact": "Площадь",
  "protec_zone": "Зона защиты",
  "descrip_area1": "Описание зоны_1",
  "descrip_area2": "Описание зоны_2",
  "full_descrip1": "Полное описание_1",
  "relief": "Рельеф",
  "climate": "Климат",
  "soilcover": "Почвенный покров",
  "hydrology": "Гидрология",
  "flora": "Флора",
  "forestfund": "Лесной фонд",
  "animals": "Животные",
  "full_descrip2": "Полное описание_2",
  "vegetation": "Вегетация",
  "full_descrip3": "Полное описание_3",
  "full_descrip4": "Полное описание_4",
  "full_descrip5": "Полное описание_5",
  "hist_note": "Историческая заметка",
  "real_state": "Состояние",
  "explication": "Пояснение",
  "negative": "Отрицательное влияние",
  "owner1": "Владелец_1",
  "owner2": "Владелец_2",
  "protect": "Защита",
  "zoning": "Зонирование",
  "protect2": "Защита_2",
  "owner3": "Владелец_3",
  "recreation": "Рекреация",
  "string": "Строка",
  "string1": "Строка_1",
  "string2": "Строка_2",
  "string3": "Строка_3",
  "title1": "Заголовок_1",
  "text": "Текст",
  "group_obj": "Группа объектов",
  "subgroup": "Подгруппа",
  "x": "Долгота",
  "y": "Широта",
  "note": "Примечание",
  "details": "Детали",
  "tmp_2": "Временный_2",
  "objectid": "ID объекта",
  "tmp_1": "Временный_1",
  "delete1": "Удалено",
  "at_unit": "В ед. измерения",
  "created_at": "Создано",
  "updated_at": "Обновлено",
  "document": "Документ",
  "Действие": "Действие"
};

export const STORAGE_KEY_LAYER = 'selectedMapLayer';
export const STORAGE_KEY_TABLE = 'tableVisibility';